### ISSUE TITLE
I have some question in gen_image.py

### ISSUE THREAD

**Issue by wj7486** [autonomousvision/projected_gan#101]
Traceback (most recent call last):
  File "gen_images.py", line 143, in <module>
    generate_images() # pylint: disable=no-value-for-parameter
  File "/home/wangjie/anaconda3/envs/torch18/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/wangjie/anaconda3/envs/torch18/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/wangjie/anaconda3/envs/torch18/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wangjie/anaconda3/envs/torch18/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "gen_images.py", line 108, in generate_images
    G = legacy.load_network_pkl(f)['G_ema'].to(device) # type: ignore
  File "/home/wangjie/workspace/projected-gan-main/legacy.py", line 24, in load_network_pkl
    data = _LegacyUnpickler(f).load()
  File "/home/wangjie/workspace/projected-gan-main/legacy.py", line 69, in find_class
    return super().find_class(module, name)
ModuleNotFoundError: No module named '__builtin__'
(torch18) wangjie@vm02:~/workspace/projected-gan-main$ python gen_images.py --outdir=out --trunc=0.7 --seeds=600-605 --class=99 --network=./training-runs/00000-fastgan-CELEBA500_unlabeledall-gpus4-batch64/best_model.pkl 
Loading networks from "./training-runs/00000-fastgan-CELEBA500_unlabeledall-gpus4-batch64/best_model.pkl"...
Traceback (most recent call last):
  File "gen_images.py", line 143, in <module>
    generate_images() # pylint: disable=no-value-for-parameter
  File "/home/wangjie/anaconda3/envs/torch18/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/wangjie/anaconda3/envs/torch18/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/wangjie/anaconda3/envs/torch18/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wangjie/anaconda3/envs/torch18/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "gen_images.py", line 108, in generate_images
    G = legacy.load_network_pkl(f)['G_ema'].to(device) # type: ignore
  File "/home/wangjie/workspace/projected-gan-main/legacy.py", line 24, in load_network_pkl
    data = _LegacyUnpickler(f).load()
  File "/home/wangjie/workspace/projected-gan-main/legacy.py", line 72, in find_class
    return super().find_class(module, name)
ModuleNotFoundError: No module named '__builtin__'

I don't know how to deal.Can you help me

**Comment by anaivebird** [comment]
![$%Z(6I9`Z%`0GQ~ 5K @_3H](https://github.com/autonomousvision/projected-gan/assets/29398611/eb86c177-e86f-488e-a316-1275cb81d541)
add this to line 72 of legacy.py
