### ISSUE TITLE
KeyError: 'G' when doing a preditction

### ISSUE THREAD

**Issue by Fqlox** [autonomousvision/projected_gan#31]
Hi,

I had an error when trying to predict a output 
Training seems fine, but when I try a prediction :  `python gen_images.py --outdir=out --trunc=1.0 --seeds=0-31 --network=my_model.pkl` I got : 
```
Traceback (most recent call last):
  File "G:\Python\projected_gan\gen_images.py", line 143, in <module>
    generate_images() # pylint: disable=no-value-for-parameter
  File "G:\Anaconda3\envs\fast_gan\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "G:\Anaconda3\envs\fast_gan\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "G:\Anaconda3\envs\fast_gan\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "G:\Anaconda3\envs\fast_gan\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "G:\Python\projected_gan\gen_images.py", line 108, in generate_images
    G = legacy.load_network_pkl(f)['G_ema'].to(device) # type: ignore
  File "G:\Python\projected_gan\legacy.py", line 40, in load_network_pkl
    assert isinstance(data['G'], torch.nn.Module)
KeyError: 'G'
```

I can't figure out where the issue is.

**Comment by woctezuma** [comment]
The error means that `'G'` is not a valid key for the dictionary `data`.

**Comment by xl-sr** [comment]
as @woctezuma said, something is wrong with your pkl, the training code however should save correctly. Did you change anything, or terminate the training while it was saving?

**Comment by xl-sr** [comment]
closing for now, feel free to reopen if the issue still exists.
