### ISSUE TITLE
local variable 'feat_last' referenced before assignment

### ISSUE THREAD

**Issue by sk-zk** [autonomousvision/projected_gan#37]
Both locally and in Paperspace, training fails after "Constructing networks..." with this error:

```
Traceback (most recent call last):
  File "/storage/projected_gan/train.py", line 266, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/opt/conda/envs/pg/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/pg/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/pg/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/pg/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/storage/projected_gan/train.py", line 252, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "/storage/projected_gan/train.py", line 101, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "/storage/projected_gan/train.py", line 47, in subprocess_fn
    training_loop.training_loop(rank=rank, **c)
  File "/storage/projected_gan/training/training_loop.py", line 188, in training_loop
    img = misc.print_module_summary(G, [z, c])
  File "/storage/projected_gan/torch_utils/misc.py", line 216, in print_module_summary
    outputs = module(*inputs)
  File "/opt/conda/envs/pg/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/storage/projected_gan/pg_modules/networks_fastgan.py", line 177, in forward
    img = self.synthesis(w, c)
  File "/opt/conda/envs/pg/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/storage/projected_gan/pg_modules/networks_fastgan.py", line 81, in forward
    return self.to_big(feat_last)
UnboundLocalError: local variable 'feat_last' referenced before assignment
```

These are my params:

    --outdir=./training-runs/ --cfg=fastgan --data=pokemon.zip --batch=16 --mirror=1 --snap=50 --kimg=10000 --gpus 1

**Comment by woctezuma** [comment]
The error happens here:

https://github.com/autonomousvision/projected_gan/blob/8480bdd9150a44c31874ffa69835e10a4f6009c4/pg_modules/networks_fastgan.py#L69-L81

**Comment by sk-zk** [comment]
It's 64x64. That fixed it, ty 👍
