### ISSUE TITLE
Internet Connection Required?

### ISSUE THREAD

**Issue by Nanboy-Ronan** [autonomousvision/projected_gan#64]
Hi, I have encountered the following error at **tick 50**, while Calculating stats for the first time. I used the following command to start traninig "python train.py --outdir=./training-runs/ --cfg='fastgan' --data=./data/pokemon256.zip --gpus=4 --batch=64 --mirror=1 --snap=50 --batch-gpu=8 --kimg=1000". 

I have used the script on Colab and run it on my environment, there is no problem.  There is also no process of "calculating stats". I wonder if internet connection is required while calculating stats. If I don't have internet access, is there a way to avoid this?

```
tick 45    kimg 181.5    time 1h 50m 55s   sec/tick 145.6   sec/kimg 36.12   maintenance 0.0    cpumem 3.43   gpumem 7.35   reserved 8.52  
tick 46    kimg 185.5    time 1h 53m 20s   sec/tick 145.5   sec/kimg 36.08   maintenance 0.0    cpumem 3.43   gpumem 7.35   reserved 8.52  
tick 47    kimg 189.6    time 1h 55m 45s   sec/tick 145.4   sec/kimg 36.07   maintenance 0.0    cpumem 3.43   gpumem 7.35   reserved 8.52  
tick 48    kimg 193.6    time 1h 58m 11s   sec/tick 145.5   sec/kimg 36.08   maintenance 0.0    cpumem 3.43   gpumem 7.35   reserved 8.52  
tick 49    kimg 197.6    time 2h 00m 36s   sec/tick 145.5   sec/kimg 36.08   maintenance 0.0    cpumem 3.43   gpumem 7.35   reserved 8.52  
tick 50    kimg 201.7    time 2h 03m 02s   sec/tick 145.5   sec/kimg 36.08   maintenance 0.0    cpumem 3.43   gpumem 7.35   reserved 8.52  
Evaluating metrics...
Calculating the stats for this dataset the first time

Saving them to ./dnnlib/gan-metrics/pokemon256-inception-2015-12-05-7d1ceb56ecb53f9e4c400facb8342441.pkl
Traceback (most recent call last):
  File "/Home/pg/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Home/pg/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/Home/pg/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Home/pg/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Home/pg/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Home/pg/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/Home/pg/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/Home/pg/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x2aab864b3c10>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Home/pg/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Home/pg/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Home/pg/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.ngc.nvidia.com', port=443): Max retries exceeded with url: /v2/models/nvidia/research/stylegan3/versions/1/files/metrics/inception-2015-12-05.pkl (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2aab864b3c10>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Home/projected_gan/train.py", line 272, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/Home/pg/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Home/pg/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Home/pg/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Home/pg/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Home/projected_gan/train.py", line 258, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "/Home/projected_gan/train.py", line 101, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "/Home/projected_gan/train.py", line 47, in subprocess_fn
    training_loop.training_loop(rank=rank, **c)
  File "/Home/projected_gan/training/training_loop.py", line 418, in training_loop
    result_dict = metric_main.calc_metric(metric=metric, G=snapshot_data['G_ema'], run_dir=run_dir, cur_nimg=cur_nimg,
  File "/Home/projected_gan/metrics/metric_main.py", line 43, in calc_metric
    results = _metric_dict[metric](opts)
  File "/Home/projected_gan/metrics/metric_main.py", line 83, in fid50k_full
    fid = frechet_inception_distance.compute_fid(opts, max_real=None, num_gen=50000)
  File "/Home/projected_gan/metrics/frechet_inception_distance.py", line 25, in compute_fid
    mu_real, sigma_real = metric_utils.compute_feature_stats_for_dataset(
  File "/Home/projected_gan/metrics/metric_utils.py", line 239, in compute_feature_stats_for_dataset
    detector = get_feature_detector(url=detector_url, device=opts.device, num_gpus=opts.num_gpus, rank=opts.rank, verbose=progress.verbose)
  File "/Home/projected_gan/metrics/metric_utils.py", line 53, in get_feature_detector
    with dnnlib.util.open_url(url, verbose=(verbose and is_leader)) as f:
  File "/Home/projected_gan/dnnlib/util.py", line 446, in open_url
    with session.get(url) as res:
  File "/Home/pg/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/Home/pg/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Home/pg/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Home/pg/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.ngc.nvidia.com', port=443): Max retries exceeded with url: /v2/models/nvidia/research/stylegan3/versions/1/files/metrics/inception-2015-12-05.pkl (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2aab864b3c10>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

**Comment by woctezuma** [comment]
The error happens here:
https://github.com/autonomousvision/projected_gan/blob/fb3143bdf586c5243ceddd3dbaad74f9b9ccf446/metrics/metric_utils.py#L239

**Comment by Nanboy-Ronan** [comment]
Thank you for reply. I will try to disable it first by setting _network_snapshot_ticks_ to **None**. 

For editing the code, I also debugged today. The actual place is here https://github.com/autonomousvision/projected_gan/blob/fb3143bdf586c5243ceddd3dbaad74f9b9ccf446/metrics/metric_utils.py#L53, which is not as easy to fix as I expected.

**Comment by woctezuma** [comment]
If you don't want to download models before running the code, then you could just disable computation of metrics.

https://github.com/autonomousvision/projected_gan/blob/8480bdd9150a44c31874ffa69835e10a4f6009c4/train.py#L150

**Comment by Nanboy-Ronan** [comment]
Thank you.
