### ISSUE TITLE
Exporting model to ONNX

### ISSUE THREAD

**Issue by Fqlox** [autonomousvision/projected_gan#70]
Hi, I wanted to export to ONNX from a trained model.

As mentionned here : you parse a tuple as input  #49 

```
import os
import re
from typing import List, Optional, Tuple, Union

import click
import dnnlib
import numpy as np
import PIL.Image
import torch

import legacy

network_pkl = "my_model.pkl"

print('Loading networks from "%s"...' % network_pkl)
device = torch.device('cuda')
with dnnlib.util.open_url(network_pkl) as f:
    G = legacy.load_network_pkl(f)['G_ema'].to(device) # type: ignore
    
model = G

# Labels.
label = torch.zeros([1, G.c_dim], device=device)

z = torch.from_numpy(np.random.RandomState(0).randn(1, G.z_dim)).to(device).float()

# Export the model
torch.onnx.export(model,                            # model being run
                    (z, label),                          # model input (or a tuple for multiple inputs)
                    "export.onnx",                  # where to save the model (can be a file or file-like object)
                    export_params=True,             # store the trained parameter weights inside the model file
                    opset_version=9,                # the ONNX version to export the model to
                    do_constant_folding=True,       # whether to execute constant folding for optimization
                    input_names = ['latent', 'label'],       # the model's input names
                    output_names = ['image']        # the model's output names
                    )


```

It still gives error : 

```
G:\Python\fastgan2\projected_gan\pg_modules\blocks.py:40: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert nc % 2 == 0, 'channels dont divide 2!'
G:\Python\fastgan2\projected_gan\pg_modules\blocks.py:41: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  nc = int(nc/2)
G:\Anaconda3\envs\fast_gan\lib\site-packages\torch\onnx\symbolic_helper.py:381: UserWarning: You are trying to export the model with onnx:Upsample for ONNX opset version 9. This operator might cause results to not match the expected results by PyTorch.
ONNX's Upsample/Resize operator did not match Pytorch's Interpolation until opset 11. Attributes to determine how to transform the input were added in onnx:Resize in opset 11 to support Pytorch's behavior (like coordinate_transformation_mode and nearest_mode).
We recommend using opset 11 and above for models using this operator.
  warnings.warn("You are trying to export the model with " + onnx_op + " for ONNX opset version "
G:\Anaconda3\envs\fast_gan\lib\site-packages\torch\onnx\symbolic_helper.py:258: UserWarning: ONNX export failed on adaptive_avg_pool2d because input size not accessible not supported
  warnings.warn("ONNX export failed on " + op + " because " + msg + " not supported")
Traceback (most recent call last):
  File "G:\Python\fastgan2\projected_gan\export.py", line 29, in <module>
    torch.onnx.export(model,                            # model being run
  File "G:\Anaconda3\envs\fast_gan\lib\site-packages\torch\onnx\__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "G:\Anaconda3\envs\fast_gan\lib\site-packages\torch\onnx\utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "G:\Anaconda3\envs\fast_gan\lib\site-packages\torch\onnx\utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "G:\Anaconda3\envs\fast_gan\lib\site-packages\torch\onnx\utils.py", line 497, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "G:\Anaconda3\envs\fast_gan\lib\site-packages\torch\onnx\utils.py", line 216, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "G:\Anaconda3\envs\fast_gan\lib\site-packages\torch\onnx\__init__.py", line 373, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "G:\Anaconda3\envs\fast_gan\lib\site-packages\torch\onnx\utils.py", line 1032, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "G:\Anaconda3\envs\fast_gan\lib\site-packages\torch\onnx\symbolic_helper.py", line 172, in wrapper
    return fn(g, *args, **kwargs)
  File "G:\Anaconda3\envs\fast_gan\lib\site-packages\torch\onnx\symbolic_opset9.py", line 1346, in batch_norm
    weight, bias, running_mean, running_var = sym_help._batchnorm_helper(g, input, weight, bias, running_mean, running_var)
  File "G:\Anaconda3\envs\fast_gan\lib\site-packages\torch\onnx\symbolic_helper.py", line 726, in _batchnorm_helper
    raise RuntimeError("Unsupported: ONNX export of batch_norm for unknown "
RuntimeError: Unsupported: ONNX export of batch_norm for unknown channel size.
```

Thanks in advance

**Comment by xl-sr** [comment]
it seems that ONNX does not handle the abstractions in the code, and it will be a major change to support it. I think it should be possible to write a converter function for the BatchNorms, I am happy to accept PRs on this issue.
