### ISSUE TITLE
should pytorch version <10.0 ?

### ISSUE THREAD

**Issue by mittu1008** [autonomousvision/projected_gan#81]
there is a error message,and my torch version is 1.11.0

> ~/projected_gan $python gen_images.py --outdir=./ --trunc=0.7 --seeds=600-605 --network=./pokemon.pkl

Loading networks from "./pokemon.pkl"...
Generating image for seed 600 (0/6) ...
Traceback (most recent call last):
  File "~/projected_gan/gen_images.py", line 143, in <module>
    generate_images() # pylint: disable=no-value-for-parameter
  File "~/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "~/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "~/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/.pyenv/versions/3.9.5/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "~/projected_gan/gen_images.py", line 135, in generate_images
    img = G(z, label, truncation_psi=truncation_psi, noise_mode=noise_mode)
  File "~/.pyenv/versions/3.9.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "~/projected_gan/pg_modules/networks_fastgan.py", line 177, in forward
    img = self.synthesis(w, c)
  File "~/.pyenv/versions/3.9.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "~/projected_gan/pg_modules/networks_fastgan.py", line 63, in forward
    feat_8 = self.feat_8(feat_4)
  File "~/.pyenv/versions/3.9.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "~/.pyenv/versions/3.9.5/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "~/.pyenv/versions/3.9.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "~/.pyenv/versions/3.9.5/lib/python3.9/site-packages/torch/nn/modules/upsampling.py", line 154, in forward
    recompute_scale_factor=self.recompute_scale_factor)
  File "~/.pyenv/versions/3.9.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'

**Comment by xl-sr** [comment]
yes, see requirements in the readme.

**Comment by mittu1008** [comment]
thanks!
