### ISSUE TITLE
gen_images.py & gen_video.py issues

### ISSUE THREAD

**Issue by nerdyrodent** [autonomousvision/projected_gan#9]
Hi, I'm getting the following issues when trying to generate images or videos, if anyone has any ideas?

``python gen_images.py --outdir=out --trunc=1.0 --seeds=4096-4105  --network=training-runs/00000-fastgan-faces_512-gpus1-batch64/network-snapshot.pkl``

Results in:
```
Loading networks from "training-runs/00000-fastgan-faces_512-gpus1-batch64/network-snapshot.pkl"...
Generating image for seed 4096 (0/10) ...
Traceback (most recent call last):
  File "/home/nerdy/github/projected_gan/gen_images.py", line 143, in <module>
    generate_images() # pylint: disable=no-value-for-parameter
  File "/home/nerdy/anaconda3/envs/pg/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/nerdy/anaconda3/envs/pg/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/nerdy/anaconda3/envs/pg/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nerdy/anaconda3/envs/pg/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/nerdy/github/projected_gan/gen_images.py", line 135, in generate_images
    img = G(z, label, truncation_psi=truncation_psi, noise_mode=noise_mode)
  File "/home/nerdy/anaconda3/envs/pg/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nerdy/github/projected_gan/pg_modules/networks_fastgan.py", line 173, in forward
    img = self.synthesis(w, c)
  File "/home/nerdy/anaconda3/envs/pg/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nerdy/github/projected_gan/pg_modules/networks_fastgan.py", line 60, in forward
    feat_4 = self.init(input)
  File "/home/nerdy/anaconda3/envs/pg/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nerdy/github/projected_gan/pg_modules/blocks.py", line 65, in forward
    return self.init(noise)
  File "/home/nerdy/anaconda3/envs/pg/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nerdy/anaconda3/envs/pg/lib/python3.9/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/nerdy/anaconda3/envs/pg/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/nerdy/anaconda3/envs/pg/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 916, in forward
    return F.conv_transpose2d(
RuntimeError: Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same
```
With gen_video:

``python gen_video.py --output=vid.mp4 --seeds=4096-4105  --network=training-runs/00000-fastgan-faces_512-gpus1-batch64/network-snapshot.pkl``

```Loading networks from "training-runs/00000-fastgan-faces_512-gpus1-batch64/network-snapshot.pkl"...
Traceback (most recent call last):
  File "/home/nerdy/github/projected_gan/gen_video.py", line 190, in <module>
    generate_images() # pylint: disable=no-value-for-parameter
  File "/home/nerdy/anaconda3/envs/pg/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/nerdy/anaconda3/envs/pg/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/nerdy/anaconda3/envs/pg/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nerdy/anaconda3/envs/pg/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/nerdy/github/projected_gan/gen_video.py", line 185, in generate_images
    gen_interp_video(G=G, mp4=output, bitrate='12M', grid_dims=grid, num_keyframes=num_keyframes, w_frames=w_frames, seeds=seeds, shuffle_seed=shuffle_seed, psi=truncation_psi, class_idx=class_idx)
  File "/home/nerdy/github/projected_gan/gen_video.py", line 74, in gen_interp_video
    ws = G.mapping(z=zs, c=label, truncation_psi=psi)
  File "/home/nerdy/anaconda3/envs/pg/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'truncation_psi
```

**Comment by xl-sr** [comment]
fixed both! You might need to retrain your model though (or load the state_dict manually). 

On a sidenote, for portrait datasets, I recommend using the StyleGAN2 backbone, we show the FastGAN samples in the limitations ;)
